// <auto-generated />
using System;
using API_Emprestimos.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_Emprestimos.Migrations.BaseDb
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20210726174659_PedidoAceitoNullable")]
    partial class PedidoAceitoNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_Emprestimos.Models.AceiteEmprestimo", b =>
                {
                    b.Property<int>("ACEITEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ACEITO")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CREDORUSUARIOID")
                        .HasColumnType("int");

                    b.Property<int?>("OFERTAID")
                        .HasColumnType("int");

                    b.Property<int?>("PEDIDOID")
                        .HasColumnType("int");

                    b.Property<int?>("REQUERENTEUSUARIOID")
                        .HasColumnType("int");

                    b.Property<double>("TAXAFINAL")
                        .HasColumnType("float");

                    b.Property<double>("TEMPOFINAL")
                        .HasColumnType("float");

                    b.Property<double>("TIPOTEMPOFINAL")
                        .HasColumnType("float");

                    b.Property<double>("VALORFINAL")
                        .HasColumnType("float");

                    b.Property<double>("VALORINICIAL")
                        .HasColumnType("float");

                    b.HasKey("ACEITEID");

                    b.HasIndex("CREDORUSUARIOID");

                    b.HasIndex("OFERTAID");

                    b.HasIndex("PEDIDOID");

                    b.HasIndex("REQUERENTEUSUARIOID");

                    b.ToTable("AceiteEmprestimo");
                });

            modelBuilder.Entity("API_Emprestimos.Models.OfertaEmprestimo", b =>
                {
                    b.Property<int>("OFERTAID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CANCELADO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CRIADO")
                        .HasColumnType("datetime2");

                    b.Property<int>("PEDIDOID")
                        .HasColumnType("int");

                    b.Property<double>("TAXA")
                        .HasColumnType("float");

                    b.Property<int>("TEMPO")
                        .HasColumnType("int");

                    b.Property<int>("TIPOTEMPO")
                        .HasColumnType("int");

                    b.Property<int?>("USUARIOID")
                        .HasColumnType("int");

                    b.HasKey("OFERTAID");

                    b.HasIndex("PEDIDOID");

                    b.HasIndex("USUARIOID");

                    b.ToTable("OfertaEmprestimo");
                });

            modelBuilder.Entity("API_Emprestimos.Models.PedidoEmprestimo", b =>
                {
                    b.Property<int>("PEDIDOID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ACEITO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CRIADO")
                        .HasColumnType("datetime2");

                    b.Property<int?>("USUARIOID")
                        .HasColumnType("int");

                    b.Property<double>("VALOR")
                        .HasColumnType("float");

                    b.HasKey("PEDIDOID");

                    b.HasIndex("USUARIOID");

                    b.ToTable("PedidoEmprestimo");
                });

            modelBuilder.Entity("API_Emprestimos.Models.Usuario", b =>
                {
                    b.Property<int>("USUARIOID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BAIRRO")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("CEP")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CIDADE")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ENDERECO")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ESTADO")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("USUARIOID");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("EMAIL")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("API_Emprestimos.Models.AceiteEmprestimo", b =>
                {
                    b.HasOne("API_Emprestimos.Models.Usuario", "CREDOR")
                        .WithMany()
                        .HasForeignKey("CREDORUSUARIOID");

                    b.HasOne("API_Emprestimos.Models.OfertaEmprestimo", "OFERTA")
                        .WithMany()
                        .HasForeignKey("OFERTAID");

                    b.HasOne("API_Emprestimos.Models.PedidoEmprestimo", "PEDIDO")
                        .WithMany()
                        .HasForeignKey("PEDIDOID");

                    b.HasOne("API_Emprestimos.Models.Usuario", "REQUERENTE")
                        .WithMany()
                        .HasForeignKey("REQUERENTEUSUARIOID");

                    b.Navigation("CREDOR");

                    b.Navigation("OFERTA");

                    b.Navigation("PEDIDO");

                    b.Navigation("REQUERENTE");
                });

            modelBuilder.Entity("API_Emprestimos.Models.OfertaEmprestimo", b =>
                {
                    b.HasOne("API_Emprestimos.Models.PedidoEmprestimo", "PEDIDO")
                        .WithMany("Ofertas")
                        .HasForeignKey("PEDIDOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Emprestimos.Models.Usuario", "USUARIO")
                        .WithMany()
                        .HasForeignKey("USUARIOID");

                    b.Navigation("PEDIDO");

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("API_Emprestimos.Models.PedidoEmprestimo", b =>
                {
                    b.HasOne("API_Emprestimos.Models.Usuario", "USUARIO")
                        .WithMany()
                        .HasForeignKey("USUARIOID");

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("API_Emprestimos.Models.PedidoEmprestimo", b =>
                {
                    b.Navigation("Ofertas");
                });
#pragma warning restore 612, 618
        }
    }
}
